# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ed87408b9481e40a03a1f655c83785980857d1d7ac402b16055ee1e160296238ec7871b3047564264014ec308bfa3c3f38948ed65be98c0798b4f82fc788e40

test:
  secret_key_base: 0e2b94fb5e04dff07f97322d0688beaab64412ddb5de5541c753706131876446c8b849f0ab10004e6ddecb0e07d3382324862343d35e800931ac18a74e1bd6f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
